apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: dockerhub-credentials
data:
  .dockerconfigjson: {{ printf `{"auths":{"https://index.docker.io/v1/":{"username":"%s","password":"%s"}}}` (.Values.dockerhubUsername) (.Values.dockerhubPassword) | b64enc }}
