apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: dockerhub-credentials
data:
  .dockerconfigjson: {{ printf `{"auths":{"https://index.docker.io/v1/":{"username":"%s","password":"%s"}}}` (required "Please set dockerhubUsername" .Values.dockerhubUsername) (required "Please set dockerhubPassword" .Values.dockerhubPassword) | b64enc }}
