apiVersion: v1
kind: Secret
metadata:
  name: grafana-config
stringData:
  grafana.ini: |
    [dashboards]
    default_home_dashboard_path = "/opt/bitnami/grafana/dashboards/dashboard.json"
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        access: proxy
        editable: true
        url: "http://exercise-influxdb.{{ .Release.Namespace }}.svc.cluster.local:8086"
        basicAuth: true
        basicAuthUser: {{ .Values.influxdb.auth.admin.username }}
        basicAuthPassword: {{ .Values.influxdb.auth.admin.password }}
        secureJsonData:
          token: {{ .Values.influxdb.auth.admin.token }}
        jsonData:
          version: Flux
          organization: primary
          defaultBucket: primary
