apiVersion: v1
kind: Service
metadata:
  name: my-app-demo
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: my-app
    app.kubernetes.io/version: "1.16.0"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: my-app
