#!/usr/bin/env bash

echo "****************************************************"
echo "Configure completion and convenient aliases for bash"
echo "****************************************************"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

set -euo pipefail

TARGET_FILE="${HOME}/.bashrc"

AUTO_GEN_BEGIN_TAG="# >>> auto generated by prep script (leave this tag to allow for updates) >>>"
AUTO_GEN_END_TAG="# <<< auto generated by prep script (leave this tag to allow for updates) <<<"


# Remove any existing block
sed -i "/${AUTO_GEN_BEGIN_TAG}/,/${AUTO_GEN_END_TAG}/d" ${TARGET_FILE}

# Ensure that completion-support exists
if ! command -v complete 2>&1 >/dev/null; then
    echo "Error: completion support not installed"
    exit 1
    # TBD/TODO: install it
fi

# Append all config at the end
echo ${AUTO_GEN_BEGIN_TAG} >> ${TARGET_FILE}

# Kubernetes/kubectl stuff
if command -v kubectl 2>&1 >/dev/null; then
    echo "- Adding config for kubectl"
    # https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#enable-kubectl-autocompletion
    echo 'source <(kubectl completion bash)' >> ${TARGET_FILE}
    echo 'alias k=kubectl' >> ${TARGET_FILE}
    echo 'complete -o default -F __start_kubectl k' >> ${TARGET_FILE}
fi

echo ${AUTO_GEN_END_TAG} >> ${TARGET_FILE}


echo "Done"
